// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: one.proto

package main

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqBody) Reset() {
	*x = ReqBody{}
	mi := &file_one_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBody) ProtoMessage() {}

func (x *ReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_one_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBody.ProtoReflect.Descriptor instead.
func (*ReqBody) Descriptor() ([]byte, []int) {
	return file_one_proto_rawDescGZIP(), []int{0}
}

func (x *ReqBody) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu"`
	Mem           uint64                 `protobuf:"varint,2,opt,name=mem,proto3" json:"mem"`
	Arrived       int64                  `protobuf:"varint,3,opt,name=arrived,proto3" json:"arrived"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_one_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_one_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_one_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Result) GetMem() uint64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Result) GetArrived() int64 {
	if x != nil {
		return x.Arrived
	}
	return 0
}

var File_one_proto protoreflect.FileDescriptor

const file_one_proto_rawDesc = "" +
	"\n" +
	"\tone.proto\x12\x03one\"\x1f\n" +
	"\aReqBody\x12\x14\n" +
	"\x05Items\x18\x01 \x03(\tR\x05Items\"F\n" +
	"\x06Result\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x02 \x01(\x04R\x03mem\x12\x18\n" +
	"\aarrived\x18\x03 \x01(\x03R\aarrivedB\bZ\x06./;oneb\x06proto3"

var (
	file_one_proto_rawDescOnce sync.Once
	file_one_proto_rawDescData []byte
)

func file_one_proto_rawDescGZIP() []byte {
	file_one_proto_rawDescOnce.Do(func() {
		file_one_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_one_proto_rawDesc), len(file_one_proto_rawDesc)))
	})
	return file_one_proto_rawDescData
}

var file_one_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_one_proto_goTypes = []any{
	(*ReqBody)(nil), // 0: one.ReqBody
	(*Result)(nil),  // 1: one.Result
}
var file_one_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_one_proto_init() }
func file_one_proto_init() {
	if File_one_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_one_proto_rawDesc), len(file_one_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_one_proto_goTypes,
		DependencyIndexes: file_one_proto_depIdxs,
		MessageInfos:      file_one_proto_msgTypes,
	}.Build()
	File_one_proto = out.File
	file_one_proto_goTypes = nil
	file_one_proto_depIdxs = nil
}
